language: cpp
compiler:
  - clang
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf g++-4.9 libstdc++-4.9-dev libev-dev libevent-dev libjansson-dev libjemalloc-dev libxml2-dev libssl-dev zlib1g-dev make binutils autoconf automake autotools-dev libtool pkg-config libcunit1-dev libc-ares-dev
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - $CXX -v
env:
  - NGHTTP2_CURRENT=true
  - NGHTTP2_CURRENT=false
before_script:
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - export MRUBY_CONFIG=../mruby-http2/.travis_build_config.rb
  - sudo mkdir -p /usr/local/trusterd/htdocs
  - sudo mkdir -p /usr/local/trusterd/ssl
  - sudo cp ../mruby-http2/example/index.html /usr/local/trusterd/htdocs/.
  - cd /usr/local/trusterd/ssl
  - sudo sh -c 'yes "" | openssl req -new -days 365 -x509 -nodes -keyout server.key -out server.crt'
  - cd -
script:
  - rake
  - ./bin/mruby ../mruby-http2/example/http2_server.rb
  - ./bin/mruby ../mruby-http2/example/http2_server_tls.rb
  - ./build/host/mrbgems/mruby-http2/nghttp2/src/nghttp -v http://127.0.0.1:8080/index.html
  - ./build/host/mrbgems/mruby-http2/nghttp2/src/nghttp -v http://127.0.0.1:8080/index.html | grep -q "hello trusterd world"
  - ./build/host/mrbgems/mruby-http2/nghttp2/src/h2load -c 100 -m 100 -n 200000 http://127.0.0.1:8080/index.html
  - ./build/host/mrbgems/mruby-http2/nghttp2/src/nghttp -v https://127.0.0.1:8081/index.html
  - ./build/host/mrbgems/mruby-http2/nghttp2/src/nghttp -v https://127.0.0.1:8081/index.html | grep -q "hello trusterd world"
  - ./build/host/mrbgems/mruby-http2/nghttp2/src/h2load -c 10 -m 10 -n 50000 https://127.0.0.1:8081/index.html
  - cd ../mruby-http2 && rake test

